name: Run Crawler
on:
  push:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create virtual environment and activate
      run: |
        python -m venv venv
        source venv/bin/activate        
    - name: Install Dependencies
      run: |
        venv/bin/pip install -r requirements.txt
    - name: Download chromedriver
      run: |
        wget -q -O tmp.zip https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip
        unzip tmp.zip && rm tmp.zip
    - name: Crawl and save to DB
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REMOTE_DB_PASSWORD: ${{ secrets.REMOTE_DB_PASSWORD }}
      run: |
        venv/bin/python crawling.py
